servo_arm:
  planning_group_name: "servo_arm"
  kinematics_solver: kdl_kinematics_plugin/KDLKinematicsPlugin
  kinematics_solver_search_resolution: 0.005
  kinematics_solver_timeout: 0.05
  kinematics_solver_attempts: 3
  jiggle_fraction: 0.05
  max_safe_path_cost: 1
  joint_limits:
    servo_1_joint:
      has_velocity_limits: true
      max_velocity: 1.0
      has_acceleration_limits: true
      max_acceleration: 2.0
      has_jerk_limits: true
      max_jerk: 4.0
    servo_2_joint:
      has_velocity_limits: true
      max_velocity: 1.0
      has_acceleration_limits: true
      max_acceleration: 2.0
      has_jerk_limits: true
      max_jerk: 4.0
    servo_3_joint:
      has_velocity_limits: true
      max_velocity: 1.0
      has_acceleration_limits: true
      max_acceleration: 2.0
      has_jerk_limits: true
      max_jerk: 4.0
    servo_4_joint:
      has_velocity_limits: true
      max_velocity: 1.0
      has_acceleration_limits: true
      max_acceleration: 2.0
      has_jerk_limits: true
      max_jerk: 4.0
    servo_5_joint:
      has_velocity_limits: true
      max_velocity: 1.0
      has_acceleration_limits: true
      max_acceleration: 2.0
      has_jerk_limits: true
      max_jerk: 4.0

lifter:
  planning_group_name: "lifter"
  kinematics_solver: kdl_kinematics_plugin/KDLKinematicsPlugin
  kinematics_solver_search_resolution: 0.005
  kinematics_solver_timeout: 0.05
  kinematics_solver_attempts: 3
  jiggle_fraction: 0.05
  max_safe_path_cost: 1
  joint_limits:
    lifter_joint:
      has_velocity_limits: true
      max_velocity: 0.1
      has_acceleration_limits: true
      max_acceleration: 0.2
      has_jerk_limits: true
      max_jerk: 0.4
