arm:
  planning_group_name: "arm"
  kinematics_solver: kdl_kinematics_plugin/KDLKinematicsPlugin
  kinematics_solver_search_resolution: 0.005
  kinematics_solver_timeout: 0.05
  kinematics_solver_attempts: 3
  jiggle_fraction: 0.05
  max_safe_path_cost: 1
  joint_limits:
    shoulder_joint:
      has_velocity_limits: true
      max_velocity: 2.0
      has_acceleration_limits: true
      max_acceleration: 4.0
      has_jerk_limits: true
      max_jerk: 8.0
    elbow_joint:
      has_velocity_limits: true
      max_velocity: 2.0
      has_acceleration_limits: true
      max_acceleration: 4.0
      has_jerk_limits: true
      max_jerk: 8.0
    wrist_joint:
      has_velocity_limits: true
      max_velocity: 2.0
      has_acceleration_limits: true
      max_acceleration: 4.0
      has_jerk_limits: true
      max_jerk: 8.0
    wrist_rotation_joint:
      has_velocity_limits: true
      max_velocity: 2.0
      has_acceleration_limits: true
      max_acceleration: 4.0
      has_jerk_limits: true
      max_jerk: 8.0
